name: Daily Activity Script Run

on:
    schedule:
        - cron: '0 16 * * *'  # Runs daily at midnight UTC
    workflow_dispatch:

jobs:
    run-daily-activity:
        name: Run Daily Activity Script
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

        -   name: Install dependencies
            run: |
                pip install -r crawler/requirements.txt

        -   name: Run daily activity script
            run: python crawler_testing.py

        -   name: Update activity_KB
            run: |
                curl --location --request POST '${{secrets.DIFY_BASE_URL}}/datasets/${{secrets.ACTIVITY_DATASET_ID}}/documents/${{secrets.ACTIVITY_DOCUMENTS_ID}}/update-by-file'\
                --header 'Authorization: Bearer ${{secrets.KB_API_KEY}}' \
                --form 'data={"name": "activity_result.txt", "indexing_technique": "high_quality", "process_rule": {"rules": {"pre_processing_rules": [{"id": "remove_extra_spaces", "enabled": true}, {"id": "remove_urls_emails", "enabled": false}], "segmentation": {"separator": "=END=", "max_tokens": 4000, "overlap": 0}}, "mode": "custom"}};type=application/json' \
                --form 'file=@crawler/output/activity/activity_result.txt'


        -   name: Upload activity_result.json to remote server
            run: |
                curl -v -X POST "${{secrets.UPDATE_ACT_INFO_URL}}?file_type=json" \
                    -F "file=@crawler/save/activity/activity_result.json"

        -   name: Update act_info
            run: |
                curl -X POST ${{secrets.DIFY_BASE_URL}}/workflows/run \
                --header 'Authorization: Bearer ${{secrets.UPDATE_ACT_INFO_API_KEY}}' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "inputs": {},
                    "response_mode": "blocking",
                    "user": "github"
                }'