name: Daily Activity Script Run

env:
    DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
    KB_API_KEY: ${{ secrets.KB_API_KEY }}

    DATASET_ID: ${{ secrets.ACTIVITY_DATASET_ID }}
    DOCUMENT_ID: ${{ secrets.ACTIVITY_DOCUMENTS_ID }}
    UPDATE_ACT_INFO_URL: ${{secrets.UPDATE_ACT_INFO_URL}}
    UPDATE_ACT_INFO_API_KEY: ${{secrets.UPDATE_ACT_INFO_API_KEY}}

on:
    schedule:
        - cron: '0 16 * * *'  # Runs daily at midnight UTC
    workflow_dispatch:

jobs:
    run-daily-activity:
        name: Run Daily Activity Script
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4


        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'


        -   name: Install dependencies
            run: |
                pip install -r crawler/requirements.txt


        -   name: Run daily activity script
            run: python crawler_activity.py


        -   name: Update activity_KB
            run: python update_activity_kb.py


        -   name: Upload activity_result.json to remote server
            run: |
                curl -v -X POST "$UPDATE_ACT_INFO_API_KEY?file_type=json" \
                    -F "file=@crawler/save/activity/activity_result.json"


        -   name: Update act_info
            run: |
                curl -X POST $DIFY_BASE_URL/workflows/run \
                --header 'Authorization: Bearer $UPDATE_ACT_INFO_API_KEY' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                    "inputs": {},
                    "response_mode": "blocking",
                    "user": "github"
                }'
